theme: minima
title: KEIEN
description: Programming, tech and thoughts💡
github_username: guiyuanju
github_repo: "blog-ns"
baseurl: "/blog-ns"

minima:
  social_links:
    x: lasvice
    github: guiyuanju

use_math: true
show_description: true
show_image: true
show_tags: true
