title: k
github_username: guiyuanju
github_repo: "guiyuanju.github.io"
baseurl: "/"
email: lasviceju@outlook.com
favicon: "logo.png"

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

permalink: /:slug.html

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

exclude:
  - .jektex-cache

# use_math: true
# show_description: true
# show_image: true
# show_tags: true
